### ISSUE TITLE
Fix formatting on single recipe page

### ISSUE THREAD

**Issue by callumhauber** [Web-Science-Team/plan-and-pantry#23]
The sidebar isn't all the way to the left, and there's the same kind of scaling issues with the sidebar as there is on the home page (#22)

![chrome_K0WougyWhI](https://user-images.githubusercontent.com/29618911/165007738-81e2874a-d006-4849-baf9-d103e6888ce1.png)

**Comment by fernap4** [comment]
![image](https://user-images.githubusercontent.com/61203598/165178976-7591361b-812c-4e75-9835-5699880a1e9e.png)

Is this better?
This is in the pantry branch btw

**Comment by callumhauber** [comment]
Issue fixed by #29
